### ISSUE TITLE
Unable to "connect" to libcoap-based server due to invalid ping

### ISSUE THREAD

**Issue by hirokiht** [tzolov/coap-shell#1]
This issue is caused by invalid Empty Message in Californium "ping" implementation.

Hence when the ping "fails", the connection is regarded as invalid, even though the server is perfectly fine.

Unable to "connect", makes it impossible to use other commands (such as GET), as it relies on connect successful to send other requests.

**Comment by tzolov** [comment]
Hi @hirokiht, thanks for the feedback! But unfortunately the comment doesn't make it clear if this is an issue you are facing or a recommendation? 

If the former,  could you please provide an example or better test?  

The Shell leverages the [Californium (2.0.0-M10)](https://github.com/eclipse/californium) libraries for both CoAP and DTLS communication. No low-lever protocol stacks are implemented into the shell itself.

**Comment by hirokiht** [comment]
I thought the option is added to the request in this project, as I take a deeper took, the problem is in Californium "ping" implementation.

**Comment by hirokiht** [comment]
I opened an issue in the Californium for the ping implementation:
#https://github.com/eclipse/californium/issues/677

**Comment by tzolov** [comment]
Thanks @hirokiht for spotting and raising this issue!

Until it is resolved on the Californium side, in the Shell perhaps you can disable the the `ping` call during the CoAP serve connection, so hopefully you will be able to use the shell for other commands.  Or if you prefer i can do it myself? 

Also do you know any publicly accessible CoAP server that uses `libcoap` so i can use it for testing the shell compatibility?

**Comment by tzolov** [comment]
@hirokiht i've just released a new coap-shell (1.0.7) that doesn't perform ping at connection time but relies on the discovery command to determine if the server is available.  Please give it a try and let me know if it helps.
Still if you are aware of any public libcoap resource i can connect to let me know.
