### ISSUE TITLE
javax.xml.bind dependency error when using JAVA v11

### ISSUE THREAD

**Issue by cdh4u** [tzolov/coap-shell#2]
As javax.xml.bind has been deprecated from Java v11, running './mvnw clean install' will cause an error.

To solve it, you need to add an javax.xml.bind dependency to the pom.xml file.

```
<dependency>
  <groupId>javax.xml.bind</groupId>
  <artifactId>jaxb-api</artifactId>
  <version>2.3.0</version>
</dependency>
```

**Comment by tzolov** [comment]
Hi @cdh4u, i am not able to reproduce this problem, after updating to latest boot 2.2.0.RELESE.
