### ISSUE TITLE
ask about APIs

### ISSUE THREAD

**Issue by Hanningz** [tzolov/coap-shell#3]
Hi, just wonder is there any APIs can be used to build a customized android application to control the Ikea light?

**Comment by tzolov** [comment]
@Hanningz, 
IKEA's CoAP Gateway roughly follows the e OpenMobileAlliance (formerly IPSO) Smart Object specs. Check the those samples: https://github.com/tzolov/coap-shell#ikea-tr%C3%A5dfri-gateway-support
Play a bit with the shell and will figure out how to reverse the api for your needs
